_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
SOLVER:
  # STEPS: (210000, 250000)
  # MAX_ITER: 270000
  # STEPS: (210000, 250000)
  MAX_ITER: 20000
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
DATASETS:
  TRAIN: ("warpdoc_train","warpdoc_train_2")
  TEST: ("warpdoc_val",)